### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.status') in 3.4.0

### ISSUE THREAD

**Issue by colinking** [customerio/gist-web#20]
We're seeing the occasional error from gist on v3.4.0 over the past week. We don't have a stack trace, but judging by the error message, I assume it's related to https://github.com/customerio/gist-web/pull/19/files which is not checking if `response` is `null` when checking for a 304. cc @BernardGatt

**Comment by BernardGatt** [comment]
Thanks for flagging the issue Colin, we're pushing a hotfix ASAP.

**Comment by BernardGatt** [comment]
A hotfix for this issue has been deployed, please let us know if you encounter the same problem again.

Closing the issue for now.
