### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.status')

### ISSUE THREAD

**Issue by nickfla1** [customerio/gist-web#3]
## Description

The if-else statement found in the following file can lead to a TyperError if `getUserQueue` returns `undefined`:

https://github.com/customerio/gist-web/blob/43d0ffb22dea235445b088b910281ff925bd690c/src/managers/queue-manager.js#L111-L122

**Comment by BernardGatt** [comment]
Thanks for reporting this issue and submitting a pull request. We'll review it ASAP.

**Comment by BernardGatt** [comment]
We released a hotfix for this issue earlier today. Please let us know if you have any further issues.
