### ISSUE TITLE
ESM import not working?

### ISSUE THREAD

**Issue by thyming** [customerio/gist-web#44]
Hi, I'm using this module indirectly (through @customerio/cdp-analytics-browser), and bundling my app with vite. When this dependency is consumed by the dev server, i get this error:
```
✘ [ERROR] Could not resolve "html-loader!../templates/message.html"

    ../../node_modules/.pnpm/customerio-gist-web@3.6.10_webpack@5.89.0/node_modules/customerio-gist-web/src/managers/message-component-manager.js:150:25:
      150 │   var template = require("html-loader!../templates/message.html");
          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
Looking at the package.json, i see that the "import" entry in "exports" is exporting a non ESM file, and one that's not transformed by webpack (hence the html-loader require).

**Comment by clabland** [comment]
Thanks for reporting this, we'll have a look!

**Comment by clabland** [comment]
Hi @thyming, we've released an update which should fix the issue. An `pnpm install` should pull in the latest fix to @customerio/cdp-analytics browser. Please comment here if you have any more trouble!
